### PR TITLE
Modify "background threads" translation

### PR DESCRIPTION
**Pull request by zhdl889**
Depending Chinese Simplified context, it is more appropriate to translate "Background" into "后台"

& Proofreading Chinese translation

### CODE REVIEW

**Comment by teha921** [comment]
Hey thanks for the contribution.
I see some of your commits would be a helpful fix.
But others are not. And we have to spend time sifting through them.
So we are sorry we cannot merge the pull request as is.
I recommend pull request in smaller batches with smaller entropy within them.
Thanks for understanding.

**Comment by zhdl889** [comment]
Some are changes to the display format, and I think adding spaces between Chinese and English is a more standardized format. Thank you for your reply

**Comment by teha921** [comment]
Thanks for understanding, if you make a request with just the space additions first, we might pull it.

**Comment by zhdl889** [comment]
The branch has been added again... I will wait for the next version update and submit it in batches several times.😂

**Pull request closed without merging**
