### PR TITLE
Ko-kr 1.1.0 Update

### PR DESCRIPTION
**Pull request by crlotwhite**
Mail: crlotwhite@gmail.com

With the release of Synthesizer V AI, I translate added items, and something is changed, as well.

It was written based on the Japanese translation managed by Dreamtonics, and in the case of unique terms, we referred to the posts about sound and electronic.

As I was able to contact the existing author, I'm going to merge after cross-validation through code review.

In terms of Character Name, it is based on a Korean wiki [Link](https://namu.wiki/w/Synthesizer%20V)

=====
To Korean Reader

메일 : crlotwhite@gmail.com

Synthesizer V AI가 출시되면서 추가 된 항목을 번역하고 변경 사항도 있습니다.

Dreamtonics에서 관리하는 일본어 번역을 바탕으로 작성되었으며, 고유한 용어의 경우 음향 및 전자에 대한 게시물을 참조했습니다.

기존 저자에게 연락이 가능했기 때문에 코드 검토를 통해 교차 검증 후 병합 할 예정입니다.

캐릭터 명은 한글 위키 [Link] (https://namu.wiki/w/Synthesizer%20V)를 기준으로합니다.

### CODE REVIEW

**Review by kz-sin — APPROVED** [review]
merge approve
thank you for 1.1.0 KR update
감사합니다 ^_^

**Comment by crlotwhite** [comment]
@Sleepwalking @teha921 
Hello maintainer.
Cross-validation is complete.
Please merge when you have time.

**Comment by crlotwhite** [comment]
Because of my mistake, this PR is closed.
Therefore re-open this PR.

**Comment by teha921** [comment]
Thanks guys! It's really helpful to have you guys collaborate because we have little ability to check if the Korean is correct.
When its more people its more assuring.

**Pull request merged**
