### PR TITLE
Add a translation of "Saki AI (Lite)"

### PR DESCRIPTION
**Pull request by zhdl889**
Add a translation of "Saki AI (Lite)"

### CODE REVIEW

**Comment by zhdl889** [comment]
By the way, when to clean up those branches that I submitted before _(:з)∠)_

**Comment by teha921** [comment]
Thanks man.
You mean delete the branches that were made to test your commits?
I'm actually not sure, but be assured your contribution is already in the master.

**Comment by zhdl889** [comment]
I'm afraid you will have one more branch every time I submit, hahahahaha😂
Thank you for your reply~
image

**Comment by teha921** [comment]
haha 😆 its easier to check on a new branch when there are a lot of commits 
We just deleted the two branches 👍

**Pull request merged**
