### PR TITLE
Ko-KR

### PR DESCRIPTION
**Pull request by kz-sin**
SynthV R2 pro 韓国語UI
E-mail:: kimzipsin@gmail.com

### CODE REVIEW

**Comment by teha921** [comment]
Thank you very much!
image

**Comment by teha921** [comment]
Yes that is no problem. You can try it on your end as well.

**Comment by kz-sin** [comment]
I'm sorry, I tried putting the txt file in the folder, but the Korean UI
was not applied. How can I apply the UI?

2020년 8월 2일 (일) 오후 2:54, teha921 <notifications@github.com>님이 작성:

**Comment by teha921** [comment]
Did you put the `.txt` extension?

**Comment by kz-sin** [comment]
of course.
[image: image.png]

2020년 8월 2일 (일) 오후 5:38, teha921 <notifications@github.com>님이 작성:

**Comment by teha921** [comment]
Ok. Then its probably the file location.
If you try with the other language files and they also don't work that would be confirmation.
What OS do you use and where do you place the txt file?
Sorry I can't see the image.

**Comment by kz-sin** [comment]
I am using Windows10 and the file location is C:\Program Files\Synthesizer
V Studio Pro. I didn't know which folder to put in, so I put it in every
folder and tried it.

2020년 8월 2일 (일) 오후 6:40, teha921 <notifications@github.com>님이 작성:

**Comment by teha921** [comment]
On macOS it would be something like `/Library/Application Support/Dreamtonics/Synthesizer V Studio/translations/ko-kr.txt`.
One way is to search for all the directories named `translations` and put it there.

**Comment by kz-sin** [comment]
You got the wrong folder! On Windows, it seems to be applied by putting it
in C:\Users\ppjang\Documents\Dreamtonics\Synthesizer V Studio\translations.
Thank you very much!

2020년 8월 2일 (일) 오후 7:26, teha921 <notifications@github.com>님이 작성:

**Comment by kz-sin** [comment]
*you > I

2020년 8월 2일 (일) 오후 7:35, 김짚신 <kimzipsin@gmail.com>님이 작성:

**Pull request merged**
